{
	"base_info": [{
		"title": "北京市人口总量数据分析",
		"describe": "人口单位:万",
		"font": "20",
		"backgroud": "blank",
		"title_position": "center",

	}, ],

	"data": {
		"人口": {
			"data": {
				"2013": {
					"1": {
						"东城区": {
							"total_population": 300,
							"male_total_population": 155,
							"famale_total_population": 145,
							"already_employed": 289,
						},
						"海淀区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"朝阳区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"丰台区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"门头沟区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"石景山区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"房山区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"通州区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"顺义区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"昌平区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"大兴区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"怀柔区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"平谷区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"延庆区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"密云区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
					},
					"2": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"3": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"4": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"5": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"6": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"7": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"8": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"9": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"10": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"11": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"12": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
				},

				"2014": {
					"1": {
						"东城区": {
							"total_population": 300,
							"male_total_population": 155,
							"famale_total_population": 145,
							"already_employed": 289,
						},
						"海淀区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"朝阳区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"丰台区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"门头沟区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"石景山区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"房山区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"通州区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"顺义区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"昌平区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"大兴区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"怀柔区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"平谷区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"延庆区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
						"密云区": {
							"total_population": 344,
							"male_total_population": 175,
							"famale_total_population": 169,
							"already_employed": 333,
						},
					},
					"2": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"3": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"4": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"5": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"6": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"7": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"8": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"9": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"10": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"11": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},
					"12": {
						"东城区": {
							"total_population": "155555",
							"famale_total_population": ""
						},
						"海淀区": {},
						"朝阳区": {},
						"丰台区": {},
						"门头沟区": {},
						"石景山区": {},
						"房山区": {},
						"通州区": {},
						"顺义区": {},
						"昌平区": {},
						"大兴区": {},
						"怀柔区": {},
						"平谷区": {},
						"延庆区": {},
						"密云区": {},
					},

				},
				"2015": {
					"dd": "dd"
				},
				"2016": {
					"dd": "dd"
				},
				"2017": {
					"dd": "dd"
				},
			},

			"type": {
				"color_map": {
					"legend": ["100万人以下", "100万~200万", "300w万~400万", "400万~500万", "500万以上"]
				},
				"migration_map": {
					"dd": "dd"
				},
				"bitmap": {
					"dd": "dd"
				}
			}

		},
		"城镇": {
			"data": "ddd"

		}

	}

}